### ISSUE TITLE
Would like to ask if relicense is possible.

### ISSUE THREAD

**Issue by ultimaweapon** [Impalabs/applevisor#2]
Hi,

I would like to use `applevisor-sys` on my project. The problem is it is licensed under GPL. Is it possible to relicense this?

**Comment by 0xLyte** [comment]
Hi,

I've pushed a new version that cleans a few things up and switches to more permissive licenses (https://github.com/Impalabs/applevisor/tree/v0.1.3).
I'm closing this for now, but let me know if you have other issues.

**Comment by ultimaweapon** [comment]
Thanks!
